version: '3.8'

services:
    nlp:
        build:
            context: docker
            dockerfile: Dockerfile
        volumes:
            - .:/nlp-unibuc-website
        ports:
            - 8000:8000
        command: "make serve"
        tty: true
